version: '3.4'

services:
  api:
    container_name: api
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      - GIN_MODE=debug
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/app/local/gcloud.json
      - GCP_PROJECT_ID=fiuba-taller3
    ports:
      - "8080:8080"

# Create the external network with
# docker network create taller3
networks:
  default:
    external: true
    name: taller3